name: Build

on:
    workflow_call:
        inputs:
            node_version:
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 10.12.4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18.x"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Build project
              run: pnpm build
