name: CI Pipeline

on:
    pull_request:
        branches: [main, dev, qa]
        types: [opened, reopened, synchronize]

jobs:
    lint:
        uses: ./.github/workflows/lint-and-format.yml
        with:
            node_version: "18.x"

    build:
        uses: ./.github/workflows/build.yml
        with:
            node_version: "18.x"
